name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Paso 3: Instalar dependencias de Composer
      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-interaction --prefer-dist

      # Paso 4: Instalar dependencias de npm con Node.js 20
      - name: Install Node.js and NPM dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | sudo bash -  # Instalar Node.js 20 LTS
          sudo apt-get update
          sudo apt-get install -y nodejs  # Instalar Node.js
          npm install  # Instalar dependencias de npm

      # Paso 5: Generar los activos con Vite
      - name: Build assets with Vite
        run: |
          npm run build  # Esto generará el archivo manifest.json en /public/build

      # Paso 6: Crear el archivo .env de pruebas con los secretos (si es necesario)
      - name: Set up .env file
        run: |
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "APP_ENV=production" >> .env  # Cambiar a producción para despliegue

      # Paso 7: Desplegar a Hostinger mediante SSH con contraseña
      - name: Deploy to Hostinger via SSH (with password)
        env:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          # Instalar sshpass y npm para asegurar que todo esté disponible
          sudo apt-get install -y sshpass nodejs npm sudo
          
          # Verificar si la conexión SSH funciona correctamente
          echo "Verificando la conexión SSH con: $USERNAME@$HOST:$PORT"
          
          # Conexión SSH usando sshpass (contraseña) y ejecutar el despliegue
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no -p $PORT $USERNAME@$HOST << 'EOF'
          
          # Verificación: Comprobar si la conexión SSH está funcionando correctamente
          echo "Verificando el usuario actual en el servidor"
          whoami  # Mostrar el usuario con el que estás conectado

          echo "Verificando si estamos en el directorio correcto"
          pwd  # Mostrar el directorio de trabajo actual

          # Comprobar si la ruta koalacordisimple.jcomtec.com existe
          echo "Comprobando si la ruta $HOME/domains/koalacordisimple.jcomtec.com existe"
          if [ ! -d "$HOME/domains/koalacordisimple.jcomtec.com" ]; then
            echo "El directorio no existe. Clonando el repositorio."
            git clone https://github.com/EdgarC97/CordiSimpleV2.git $HOME/domains/koalacordisimple.jcomtec.com
          fi

          # Asegurarse de estar en el directorio correcto
          cd $HOME/domains/koalacordisimple.jcomtec.com

          # Verificar si el repositorio se clonó correctamente
          if [ ! -d ".git" ]; then
            echo "El directorio no es un repositorio Git. Abortando despliegue."
            exit 1
          fi

          # Actualizar el repositorio
          git pull origin main  # Asegurarse de tener la última versión del repositorio

          # Continuar con el despliegue si todo es correcto
          composer install --no-dev --optimize-autoloader  # Instalar dependencias de PHP
          npm install --production  # Instalar dependencias de npm
          npm run build  # Generar los activos

          # Verificar si el archivo .env.example existe
          if [ ! -f ".env.example" ]; then
            echo ".env.example no encontrado. Usando un .env predeterminado."
            cp .env.example .env  # Copiar el archivo .env
          fi

          # Ejecutar comandos de Laravel
          if [ -f "artisan" ]; then
            php artisan key:generate  # Generar la clave de la aplicación
            php artisan config:cache  # Limpiar caché de configuración
            php artisan route:cache  # Limpiar caché de rutas
            php artisan migrate --force  # Ejecutar migraciones
            sudo chown -R www-data:www-data storage bootstrap/cache  # Ajustar permisos
          else
            echo "No se encontró el archivo artisan. Abortando despliegue."
            exit 1
          fi

          EOF
